### PR TITLE
glt - Add UCSBOrganization database

### LINKED ISSUE #25: Create database table for UCSBOrganization
Create database table for UCSBOrganization

# Acceptance Criteria:

- [x] There is an `@Entity` class called UCSBOrganization.java
- [x] There is a `@Repository` class called UCSBOrganizationRepository.java
- [x] When you start up the repo on localhost, you can see the table
      using the H2 console (see the file `docs/h2-database.md` for 
      instructions.)
- [ ] When you deploy the app to Heroku, you can see the table
      using the psql command (See `Accessing Database Console` in the
      main `README.md` file for instructions.)

### PR DESCRIPTION
**Pull request by coding-me-softly**
In this PR we add a database to the Spring backend capable of storing UCSB Organizations.  This PR adds the required Entity and Repository classes.

Closes #25

### CODE REVIEW

**Review by bhuang01 — APPROVED** [review]
LGTM

**Review by peterlototsky — APPROVED** [review]
All columns present, LGTM.

**Review by sophiacheng01 — APPROVED** [review]
LGTM

**Comment by dengkevin** [comment]
LGTM

**Review by dengkevin — APPROVED** [review]
LGTM

**Review by myangichael — APPROVED** [review]
LGTM

**Pull request merged**
