### PR TITLE
bh - Adding Recommendation Request controller

### PR DESCRIPTION
**Pull request by bhuang01**
Also tested the h2 database. Some functionality is questionable, but it is working
- Date and time format is confusing, not user friendly
- Database entries can be updated with POST as well as PUT

### CODE REVIEW

**Review by coding-me-softly — COMMENTED** [review]
Removed original: sorry I was testing on the wrong branch and gave a bunch of wrong feedback :smiling_face_with_tear:

**Review by coding-me-softly — CHANGES_REQUESTED** [review]
LGTM, all the features are working on my computer.

I have some tips to pass the mutation tests:

image
Removing the line above still passes the tests because it turns out the the default value of a boolean variable like `done` is `false`.  Every mutation like this one can be caught by always setting each variable to a non-default value in the test cases for the POST api.
image
For the tests above, the line 104 mutation lives because line 104 does nothing. The id is always going to be the same and this entire line can be removed, I think.  For the other lines, you can catch those mutation by making your tests update *every single variable* in the database entry.  Because if some of the entries remain the same in your test case, the mutation will remove that line and live because the overall effect was that that line wasn't needed for that test case.

**Review by coding-me-softly — APPROVED** [review]
LGTM

**Review by sophiacheng01 — APPROVED** [review]
LGTM

**Review by peterlototsky — APPROVED** [review]
LGTM

**Pull request merged**
