### PR TITLE
bh - Add Recommendation Request database

### LINKED ISSUE #20: Create database table for Recommendation
Create database table for Recommendation

# Acceptance Criteria:

- [x] There is an `@Entity` class called Recommendation.java
- [x] There is a `@Repository` class called RecommendationRepository.java
- [x] When you start up the repo on localhost, you can see the table
      using the H2 console (see the file `docs/h2-database.md` for 
      instructions.)
- [ ] When you deploy the app to Heroku, you can see the table
      using the psql command (See `Accessing Database Console` in the
      main `README.md` file for instructions.)

### PR DESCRIPTION
**Pull request by bhuang01**
In this PR we add a database to the Spring backend capable of storing Recommendation Requests. This PR adds the required Entity and Repository classes.

Closes #20

### CODE REVIEW

**Review by coding-me-softly — APPROVED** [review]
LGTM. I think the classes are meant to be `RecommendationRequest` and `RecommendationRequestRepository`, but it's probably fine as is.

**Review by peterlototsky — APPROVED** [review]
LGTM, all the database columns match up as in the documentation.

**Comment by coding-me-softly** [comment]
> LGTM. I think the classes are meant to be `RecommendationRequest` and `RecommendationRequestRepository`, but it's probably fine as is.

I saw your Slack message, so I was wrong about this, LGTM 100%!

**Review by sophiacheng01 — APPROVED** [review]
LGTM

**Review by dengkevin — APPROVED** [review]
LGTM

**Review by myangichael — APPROVED** [review]
LGTM

**Pull request merged**
